const ACRONYMS = new Set([
  "adp",
  "ai",
  "amd",
  "aon",
  "aqr",
  "at",
  "bcg",
  "bmw",
  "bnp",
  "bny",
  "bp",
  "bt",
  "c3",
  "cme",
  "dbs",
  "dji",
  "dp",
  "drw",
  "dtcc",
  "ey",
  "f5",
  "ge",
  "gm",
  "gsa",
  "gsn",
  "hbo",
  "hcl",
  "hp",
  "hpe",
  "hrt",
  "hsbc",
  "htc",
  "ibm",
  "iit",
  "imc",
  "ivp",
  "jd",
  "kla",
  "kpmg",
  "lg",
  "llc",
  "lti",
  "maq",
  "msci",
  "ncr",
  "npci",
  "nvidia",
  "nxp",
  "pwc",
  "rbc",
  "sap",
  "sig",
  "tcs",
  "ubs",
  "ukg",
  "ust",
  "vk",
  "zs",
]);

const COMPANY_OVERRIDES = new Map<string, string>([
  ["1kosmos", "1Kosmos"],
  ["appdynamics", "AppDynamics"],
  ["appfolio", "AppFolio"],
  ["applovin", "AppLovin"],
  ["at-t", "AT&T"],
  ["blackrock", "BlackRock"],
  ["bloomreach", "Bloomreach"],
  ["bookingcom", "Booking.com"],
  ["browserstack", "BrowserStack"],
  ["bytedance", "ByteDance"],
  ["cleartrip", "ClearTrip"],
  ["clevertap", "CleverTap"],
  ["coindcx", "CoinDCX"],
  ["crowdstrike", "CrowdStrike"],
  ["darwinbox", "Darwinbox"],
  ["de-shaw", "DE Shaw"],
  ["deepmind", "DeepMind"],
  ["devops", "DevOps"],
  ["devrev", "DevRev"],
  ["docusign", "DocuSign"],
  ["doordash", "DoorDash"],
  ["ebay", "eBay"],
  ["factset", "FactSet"],
  ["github", "GitHub"],
  ["gitlab", "GitLab"],
  ["godaddy", "GoDaddy"],
  ["grubhub", "Grubhub"],
  ["hotstar", "Hotstar"],
  ["hubspot", "HubSpot"],
  ["inmobi", "InMobi"],
  ["jpmorgan", "JPMorgan"],
  ["linkedin", "LinkedIn"],
  ["liveramp", "LiveRamp"],
  ["liveperson", "LivePerson"],
  ["livspace", "Livspace"],
  ["makemytrip", "MakeMyTrip"],
  ["mathworks", "MathWorks"],
  ["mcdonalds", "McDonald's"],
  ["mckinsey", "McKinsey"],
  ["medianet", "Media.net"],
  ["mindtickle", "MindTickle"],
  ["moengage", "MoEngage"],
  ["mongodb", "MongoDB"],
  ["netapp", "NetApp"],
  ["netsuite", "NetSuite"],
  ["observeai", "Observe.AI"],
  ["okx", "OKX"],
  ["openai", "OpenAI"],
  ["opendoor", "OpenDoor"],
  ["opentext", "OpenText"],
  ["otterai", "Otter.AI"],
  ["paypal", "PayPal"],
  ["paypay", "PayPay"],
  ["payu", "PayU"],
  ["phonepe", "PhonePe"],
  ["playsimple", "PlaySimple"],
  ["ponyai", "Pony.AI"],
  ["salesforce", "Salesforce"],
  ["servicenow", "ServiceNow"],
  ["sharechat", "ShareChat"],
  ["smartnews", "SmartNews"],
  ["snapchat", "Snapchat"],
  ["soundhound", "SoundHound"],
  ["spacex", "SpaceX"],
  ["stackadapt", "StackAdapt"],
  ["t-mobile", "T-Mobile"],
  ["tiktok", "TikTok"],
  ["tripadvisor", "TripAdvisor"],
  ["tusimple", "TuSimple"],
  ["uipath", "UiPath"],
  ["vmware", "VMware"],
  ["walmart-labs", "Walmart Labs"],
  ["warnermedia", "WarnerMedia"],
  ["webmd", "WebMD"],
  ["ziprecruiter", "ZipRecruiter"],
]);

export const capitalizeWords = (str: string): string => {
  const override = COMPANY_OVERRIDES.get(str);
  if (override) return override;

  return str
    .split("-")
    .map((word) =>
      ACRONYMS.has(word.toLowerCase())
        ? word.toUpperCase()
        : word.charAt(0).toUpperCase() + word.slice(1).toLowerCase()
    )
    .join(" ");
};
