import fs from "fs/promises";
import path from "path";
import { pathToFileURL } from "node:url";
import { dedupeSitemapEntries } from "../lib/sitemap/dedupe";
import { classifySitemapPath, shouldIncludeInSitemap } from "../lib/sitemap/filters";

const DATA_DIR = path.join(process.cwd(), "public", "data");
const OUT_FILE = path.join(process.cwd(), "lib", "sitemap", "generated.ts");
const SYSTEM_DESIGN_FILE = path.join(process.cwd(), "lib", "system-design", "generated.ts");

export interface SitemapEntry {
  path: string;
  priority: number;
  changeFrequency: "weekly" | "monthly" | "daily";
}

async function loadSystemDesignSlugs(): Promise<string[]> {
  try {
    const raw = await fs.readFile(SYSTEM_DESIGN_FILE, "utf8");
    const slugs: string[] = [];
    for (const match of raw.matchAll(/"slug":\s*"([^"]+)"/g)) {
      slugs.push(match[1]);
    }
    return [...new Set(slugs)];
  } catch {
    return [];
  }
}

export async function assembleSitemapEntries(
  urls: { path: string; priority: number; changeFrequency: string }[]
): Promise<SitemapEntry[]> {
  const entries: SitemapEntry[] = [];

  for (const u of urls) {
    if (!shouldIncludeInSitemap(u.path)) continue;

    entries.push({
      path: u.path,
      priority: u.priority,
      changeFrequency: u.changeFrequency as SitemapEntry["changeFrequency"],
    });
  }

  const sdSlugs = await loadSystemDesignSlugs();
  const existing = new Set(entries.map((e) => e.path));
  if (!existing.has("/system-design") && sdSlugs.length > 0) {
    entries.push({
      path: "/system-design",
      priority: 0.8,
      changeFrequency: "monthly",
    });
  }
  for (const slug of sdSlugs) {
    const p = `/system-design/${slug}`;
    if (!existing.has(p)) {
      entries.push({ path: p, priority: 0.8, changeFrequency: "monthly" });
    }
  }

  return dedupeSitemapEntries(entries).sort((a, b) => a.path.localeCompare(b.path));
}

async function main() {
  const raw = await fs.readFile(path.join(DATA_DIR, "sitemap-urls.json"), "utf8");
  const urls = JSON.parse(raw) as {
    path: string;
    priority: number;
    changeFrequency: string;
  }[];
  const entries = await assembleSitemapEntries(urls);

  const banner =
    "// AUTO-GENERATED by scripts/build-sitemap.ts. Do not edit by hand.\n" +
    "// Run `pnpm run prebuild` (or `tsx scripts/build-sitemap.ts`) to refresh.\n\n";
  const typeDef =
    "export interface SitemapEntry {\n" +
    "  path: string;\n" +
    "  priority: number;\n" +
    '  changeFrequency: "weekly" | "monthly" | "daily";\n' +
    "}\n\n";
  const body = `export const SITEMAP_ENTRIES: SitemapEntry[] = ${JSON.stringify(entries, null, 2)};\n`;

  await fs.mkdir(path.dirname(OUT_FILE), { recursive: true });
  await fs.writeFile(OUT_FILE, banner + typeDef + body, "utf8");

  const groups: Record<string, number> = {};
  for (const e of entries) {
    const g = classifySitemapPath(e.path);
    groups[g] = (groups[g] ?? 0) + 1;
  }
  console.log(
    `Wrote ${entries.length} sitemap entries to ${path.relative(process.cwd(), OUT_FILE)}`,
    groups
  );
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
