import fs from "fs/promises";
import path from "path";
import matter from "gray-matter";

// Bake the contents of public/system-design/ into a generated TS module so the
// system-design pages can read chapters without ever touching the filesystem at
// runtime. The Cloudflare worker bundle does not ship public/ in a way that is
// readable via fs at runtime, so any fs.readdir/fs.readFile from a server
// component throws `no such file or directory, readdir '/bundle/public/...'` in
// production. Mirrors scripts/build-learn.ts.

const CONTENT_ROOT = path.join(process.cwd(), "public", "system-design");
const OUT_FILE = path.join(process.cwd(), "lib", "system-design", "generated.ts");

interface SystemDesignChapter {
  order: number;
  folder: string;
  slug: string;
  title?: string;
  heading?: string;
  video?: string;
  podcast?: string;
  content: string;
}

function extractHeading(content: string): string | undefined {
  const h1 = content.match(/^#\s+(.+)$/m) || content.match(/^##\s+(.+)$/m);
  return h1?.[1]?.trim() || undefined;
}

function computeOrder(
  folder: string,
  heading: string | undefined,
  title: string | undefined
): number {
  const folderOrderMatch = folder.match(/^(\d{1,3})/);
  const refTitle = title || heading || "";
  const titleOrderMatch = refTitle.match(/chapter\s*(\d{1,3})/i);
  const orderFromFolder = folderOrderMatch ? parseInt(folderOrderMatch[1], 10) : NaN;
  const orderFromTitle = titleOrderMatch ? parseInt(titleOrderMatch[1], 10) : NaN;
  return Number.isFinite(orderFromFolder)
    ? orderFromFolder
    : Number.isFinite(orderFromTitle)
      ? orderFromTitle
      : Number.MAX_SAFE_INTEGER;
}

async function main() {
  let dirents: { name: string; isDirectory: () => boolean }[];
  try {
    dirents = await fs.readdir(CONTENT_ROOT, { withFileTypes: true });
  } catch {
    dirents = [];
  }
  const folders = dirents.filter((d) => d.isDirectory()).map((d) => d.name);

  const chapters: SystemDesignChapter[] = [];
  for (const folder of folders) {
    try {
      const dirPath = path.join(CONTENT_ROOT, folder);
      const files = await fs.readdir(dirPath);
      const mdFile = files.find((f) => f.toLowerCase().endsWith(".md"));
      if (!mdFile) continue;
      const raw = await fs.readFile(path.join(dirPath, mdFile), "utf8");
      const parsed = matter(raw);
      const slug = (parsed.data?.slug as string | undefined)?.trim();
      if (!slug) continue;
      const title = (parsed.data?.title as string | undefined)?.trim() || undefined;
      const video = (parsed.data?.video as string | undefined)?.trim() || undefined;
      const podcast = (parsed.data?.podcast as string | undefined)?.trim() || undefined;
      const content = parsed.content;
      const heading = extractHeading(content);
      const order = computeOrder(folder, heading, title);
      chapters.push({ order, folder, slug, title, heading, video, podcast, content });
    } catch (err) {
      console.warn(`Skipping system-design folder ${folder}: ${(err as Error).message}`);
    }
  }

  chapters.sort((a, b) => {
    if (a.order !== b.order) return a.order - b.order;
    return a.folder.localeCompare(b.folder);
  });

  const banner =
    "// AUTO-GENERATED by scripts/build-system-design.ts. Do not edit by hand.\n" +
    "// Run `pnpm run prebuild` (or `tsx scripts/build-system-design.ts`) to refresh.\n\n";
  const typeDef =
    "export interface SystemDesignChapter {\n" +
    "  order: number;\n" +
    "  folder: string;\n" +
    "  slug: string;\n" +
    "  /** Raw frontmatter `title`, if present. */\n" +
    "  title?: string;\n" +
    "  /** First h1/h2 heading extracted from the markdown body. */\n" +
    "  heading?: string;\n" +
    "  /** YouTube URL from frontmatter. */\n" +
    "  video?: string;\n" +
    "  /** Spotify URL from frontmatter. */\n" +
    "  podcast?: string;\n" +
    "  /** Markdown body (frontmatter stripped). */\n" +
    "  content: string;\n" +
    "}\n\n";
  const body = `export const SYSTEM_DESIGN_CHAPTERS: SystemDesignChapter[] = ${JSON.stringify(
    chapters,
    null,
    2
  )};\n`;

  await fs.mkdir(path.dirname(OUT_FILE), { recursive: true });
  await fs.writeFile(OUT_FILE, banner + typeDef + body, "utf8");
  console.log(
    `Wrote ${chapters.length} system-design chapter(s) to ${path.relative(process.cwd(), OUT_FILE)}`
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
